version: 2

models:
  - name: int_refined__pois
    description: "Taken the most approproiate description of the poi"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - location_longitude
            - location_latitude
            - label
    columns:
      - name: id
        description: "Id of the poi"
        tests:
          - unique
          - not_null
      - name: poi_description
        description: "Description of the poi"
      - name: location_name
        description: "Name of the poi"
      - name: location_postal_code
        description: "Postal code of the poi"
      - name: location_street
        description: "Street of the poi"
      - name: rating
        description: "Rating of the poi"
      - name: features
        description: "Features of the poi"
      - name: location_longitude
        description: "Longitude of the poi"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -180 #inclusive is true by default
              max_value: 180 #inclusive is true by default
      - name: location_latitude
        description: "Latitude of the poi"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -90 #inclusive is true by default
              max_value: 90 #inclusive is true by default
      - name: label
        description: "Label of the poi in english or french"
        tests:
          - not_null
      - name: location_department
        description: "Department of the poi"
      - name: node
        description: "Geometry type in EPSG:4326 projection for the location of the poi"
        tests:
          - unique
          - not_null
