version: 2

models:
  - name: poi
    description: "Taken the most approproiate description of the poi"
    columns:
      - name: id
        description: "Id of the poi"
        tests:
          - unique
          - not_null
      - name: poi_description
        description: "Description of the poi"
      - name: location_name
        description: "Name of the poi"
      - name: location_postal_code
        description: "Postal code of the poi"
      - name: location_street
        description: "Street of the poi"
      - name: rating
        description: "Rating of the poi"
      - name: features
        description: "Features of the poi"
      - name: location_longitude
        description: "Longitude of the poi"
      - name: location_latitude
        description: "Latitude of the poi"
      - name: label
        description: "Label of the poi in english or french"
        tests:
          - not_null
      - name: location_department
        description: "Department of the poi"
      - name: osmid
        description: "OSM id of the point from osm_raw model"
        tests:
          - not_null
      - name: min_distance
        description: "Distance between the poi and the closest osm point in meters"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              max_value: 2000
